theme: jekyll-theme-midnight
# remote_theme: pages-themes/modernist@v0.2.0
title: Rune & Emilie sin side
description: En side med nyttige ting vi vil huske


# Plugins
plugins:
  - jekyll-remote-theme
